version: '3.9'

services:
  app:
    build: .
    container_name: jogos-api
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      FLASK_ENV: development
      PYTHONDONTWRITEBYTECODE: 1
      PYTHONUNBUFFERED: 1
      DATABASE_URL: postgresql://postgres:senha123@db:5432/jogosdb
    depends_on:
      - db
    command: ["/wait-for-it.sh", "db", "--", "python", "app.py"]
    restart: on-failure

  db:
    image: postgres:15
    container_name: postgres-jogos
    environment:
      POSTGRES_DB: jogosdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: senha123
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  pgdata:
